// Code generated by avro/gen. DO NOT EDIT.
package consumertest

// User is a generated struct.
type User struct {
	ID        string `avro:"id" json:"id" yaml:"id"`
	FirstName string `avro:"firstName" json:"firstName" yaml:"firstName"`
	LastName  string `avro:"lastName" json:"lastName" yaml:"lastName"`
	Email     string `avro:"email" json:"email" yaml:"email"`
}
