name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Download dependencies
        run: go mod download

      - name: Install pact-go dependencies
        run: |
          wget https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.4.28/libpact_ffi-linux-x86_64.so.gz
          gunzip libpact_ffi-linux-x86_64.so.gz
          sudo mv libpact_ffi-linux-x86_64.so /usr/local/lib/libpact_ffi.so

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install the plugin locally
        run: make install_local

      - name: Run tests
        run: gotestsum --junitfile unit-tests.xml --format pkgname

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "unit-tests.xml"
        if: always()
